return {
	{ require("nexisnv.dashboard") },
	{ require("nexisnv.themery") },
	{ require("nexisnv.toggleterm") },
	{ require("nexisnv.autocmp") },
	{ require("nexisnv.telescope") },
	{ require("nexisnv.lspconfig") },
	{ require("nexisnv.mason") },
	{ require("nexisnv.treesitter") },
	{ require("nexisnv.lazygit") },
	{ require("nexisnv.lualine") },
	{ require("nexisnv.bufferline") },
	{ require("nexisnv.projectmgr") },
	{ require("nexisnv.neotree") },
	{ "nvim-neotest/nvim-nio", },
	{ require("nexisnv.nvimdap") },
	{ require("nexisnv.neotest") },
	{ require("nexisnv.whichkey") },
	{ require("nexisnv.markdownrender") },
	{ require("nexisnv.trouble") },
	{ require("nexisnv.leap") },
	{ require("nexisnv.gitblame") },
	{ require("nexisnv.gitgutter") },
	{ require("nexisnv.visualmulti") },
	{ require("nexisnv.surround") },
	{ require("nexisnv.octo") },
}
